name: OpenHands AutoCoder

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-openhands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install OpenHands
        run: |
          pip install git+https://github.com/All-Hands-AI/OpenHands.git

      - name: Configure git
        run: |
          git config --global user.name "OpenHands Bot"
          git config --global user.email "bot@openhands.ai"

      - name: Run OpenHands agent
        run: |
          openhands --repo . --goal "
          Continue building the TikTok-style PWA, troubleshoot errors, commit working changes, and push updates automatically so Vercel deploy previews succeed. Work hands-free without manual input.
          "
