name: OpenHands AutoCoder

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-openhands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install OpenHands
        run: |
          pip install git+https://github.com/All-Hands-AI/OpenHands.git

      - name: Configure git
        run: |
          git config --global user.name "OpenHands Bot"
          git config --global user.email "bot@openhands.ai"

      - name: Add OpenHands config
        run: |
          mkdir -p .openhands
          cat > .openhands/config.yaml << 'EOF'
          llm:
            provider: openhands
            model: default
          workspace:
            base: .
          agent:
            name: "TikTokAgent"
          EOF

      - name: Run OpenHands agent
        run: |
          openhands cli \
            --config-file .openhands/config.yaml \
            -t "Continue building the TikTok-style PWA, troubleshoot errors, commit working changes, and push updates automatically so Vercel deploy previews succeed. Work hands-free without manual input."
