name: OpenHands AutoCoder

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-openhands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install OpenHands
        run: |
          pip install --upgrade pip
          pip install git+https://github.com/All-Hands-AI/OpenHands.git

      - name: Add OpenHands config (JSON format)
        run: |
          mkdir -p .openhands
          cat > .openhands/config.json << 'EOF'
          {
            "llm": {
              "provider": "openhands",
              "model": "default"
            },
            "workspace": {
              "base": "."
            },
            "agent": {
              "name": "TikTokAgent"
            }
          }
          EOF

      - name: Run OpenHands
        run: |
          openhands cli \
            --config-file .openhands/config.json \
            -t "Continue building the TikTok-style PWA, troubleshoot errors, commit working changes, and push updates automatically so Vercel deploy previews succeed. Work hands-free without manual input."
